frontend/views/user/update.php

Edit profile

---

frontend/controllers/SiteController.php
frontend/views/site/login.php
frontend/views/site/requestPasswordResetToken.php
frontend/web/css/login/style.css

Forgot password

---

frontend/views/campaign/create.php

Create campaign button

---

frontend/views/campaign/create.php
frontend/web/css/user/style.css

user background colour

---

frontend/views/layouts/header.php
frontend/web/css/user/style.css

added div tag to closer header-wrapper

added div tag to closer header-wrapper

---

frontend/views/campaign/create.php
frontend/views/campaign/view.php
frontend/web/css/homepage/structure.css

UI for view campaign

---

frontend/views/campaign/_reward.php

Create campaign UI

---

frontend/views/campaign/view.php

View UI changes

---

frontend/assets/RoadmapAsset.php
frontend/controllers/CampaignController.php
frontend/models/Roadmap.php
frontend/views/campaign/campaign_roadmap.php
frontend/views/campaign/view.php
frontend/views/layouts/header.php
frontend/web/css/roadmap/reset.css
frontend/web/css/roadmap/style.css
frontend/web/js/roadmap/main.js
frontend/web/js/roadmap/modernizr.js

roadmap added to view campaign

roadmap added to view campaign

---

frontend/views/layouts/header.php

alignment of logo in header

---

frontend/views/layouts/header.php
frontend/views/site/Music.php
frontend/views/site/art.php
frontend/views/site/manufacture.php
frontend/web/css/tab/homepageTab.css

Homepage tab UI

---

frontend/controllers/CampaignController.php
frontend/models/Roadmap.php
frontend/models/RoadmapImage.php
frontend/views/campaign/campaign_roadmap.php
frontend/views/layouts/header.php

db setup for roadmap

---

frontend/views/site/index.php

tab view in homepage

---

frontend/views/site/featured.php
frontend/views/site/index.php
frontend/web/css/tab/homepageTab.css

homepage logic and UI

---

frontend/controllers/SiteController.php
frontend/views/site/index.php

UI homepage

---

frontend/controllers/CampaignController.php
frontend/models/Comment.php
frontend/views/campaign/campaign_comments.php
frontend/views/campaign/view.php
frontend/views/site/index.php

Comments section in view campaign

Comments section in view campaign

---

frontend/views/campaign/campaign_comments.php

user image in comments section

user image in comments section

---

frontend/controllers/CampaignController.php
frontend/models/Comment.php
frontend/models/Update.php
frontend/models/UpdateImage.php
frontend/views/campaign/campaign_update.php
frontend/views/campaign/view.php

changes to update tab

---

composer.lock
frontend/views/site/index.php

images linked to view campaign

changes to index.php

---

frontend/views/campaign/create.php
frontend/views/campaign/index.php
frontend/web/js/campaign/texteditor.js

Rich text editor

---

frontend/views/campaign/create.php
frontend/views/campaign/view.php
frontend/views/layouts/footer.php
frontend/views/site/index.php
frontend/views/user/update.php
frontend/web/css/campaign/style.css
frontend/web/js/campaign/texteditor.js

Footer + create campaign

---

frontend/views/campaign/create.php
frontend/web/css/campaign/style.css

Campaign title

---

backend/views/campaign/_search.php
backend/views/campaign/index.php
backend/views/category/index.php
backend/views/frontend-user/_search.php
backend/views/frontend-user/index.php
backend/views/site/index.php
backend/views/user-backend/_search.php
backend/views/user-backend/index.php
backend/views/user-backend/update.php

Backend - layouts

---

backend/assets/ProfileAsset.php
backend/views/campaign/_search.php
backend/views/campaign/index.php
backend/views/campaign/view.php
backend/views/category/_search.php
backend/views/category/index.php
backend/views/category/update.php
backend/views/category/view.php
backend/views/email/_search.php
backend/views/email/index.php
backend/views/email/view.php
backend/views/frontend-user/_search.php
backend/views/frontend-user/index.php
backend/views/frontend-user/view.php
backend/views/layouts/header.php
backend/views/user-backend/_search.php
backend/views/user-backend/index.php
backend/views/user-backend/view.php

Backend-increment 1

---

composer.json
composer.lock
frontend/views/site/index.php

link to view campaign page by clicking the image

link to view campaign page by clicking the image

---

frontend/tests/unit/models/CampaignTest.php
frontend/tests/unit/models/CategoryTest.php
frontend/tests/unit/models/CommentTest.php
frontend/tests/unit/models/ContactFormTest.php
frontend/tests/unit/models/FaqTest.php
frontend/tests/unit/models/FundTest.php
frontend/tests/unit/models/PasswordResetRequestFormTest.php
frontend/tests/unit/models/ResetPasswordFormTest.php
frontend/tests/unit/models/RewardItemTest.php
frontend/tests/unit/models/RewardTest.php
frontend/tests/unit/models/SignupFormTest.php
frontend/tests/unit/models/UpdateTest.php
frontend/tests/unit/models/UserTest.php

Unit test for frontend

---

frontend/controllers/CampaignController.php
frontend/views/campaign/view.php

updated view campaign to track backers

updated view campaign to track backers

---

frontend/controllers/CampaignController.php
frontend/views/campaign/mycampaign.php
frontend/views/campaign/show.php
frontend/views/site/index.php

backer details to other view campaign pages

backer details to other view campaign pages

---

composer.json
composer.lock
frontend/views/campaign/create.php

https://github.com/artkost/yii2-trumbowyg

trumbowyg as text editor in create campaign

---

frontend/assets/CreateCampaignAsset.php
frontend/views/campaign/create.php
frontend/web/js/createCampaign/gen_validatorv4.js

validation for step 1 create campaign

validation for step 1 create campaign

---

frontend/controllers/CampaignController.php
frontend/models/Fund.php
frontend/views/campaign/create.php
frontend/views/campaign/fund.php
frontend/views/campaign/mycampaign.php

backed campaigns view

---

frontend/views/campaign/create.php

Create campaign layouts

---

backend/controllers/ChartsController.php
backend/views/charts/index.php
composer.json
composer.lock
frontend/views/campaign/create.php
frontend/views/campaign/fund.php

Backend dashboard

---

backend/views/layouts/header.php

Backend name

---

frontend/views/campaign/fund.php
frontend/views/campaign/show.php
frontend/views/campaign/view.php

icons are visible

---

frontend/controllers/CampaignController.php
frontend/views/campaign/update.php
frontend/views/campaign/view.php
frontend/views/layouts/footer.php
frontend/views/site/error.php

Update campaign view

---

backend/views/campaign/_form.php
frontend/controllers/CampaignController.php
frontend/views/campaign/view.php

View campaign

---

frontend/controllers/CampaignController.php
frontend/views/campaign/view.php

review campaign

---

backend/controllers/CampaignController.php
backend/models/CampaignSearchforModeration.php
backend/views/campaign/index.php
backend/views/campaign/viewDraft.php
backend/views/campaign/viewModeration.php
backend/views/campaign/viewPublish.php

backend campaign

---

backend/controllers/CampaignController.php
backend/models/CampaignSearchforDraft.php
backend/views/campaign/viewDraft.php
backend/views/campaign/viewModeration.php

tabs for backend campaign by different status of campaigns

backend campaign-tabs

---

backend/views/campaign/viewDraft.php
backend/views/campaign/viewModeration.php
backend/views/campaign/viewPublish.php

Backend campaign page name

---

composer.json
composer.lock
frontend/controllers/CampaignController.php
frontend/views/campaign/campaign_comments.php
frontend/views/campaign/delete.php
frontend/views/campaign/update.php
frontend/views/campaign/view.php

comment campaign updated

---

frontend/views/campaign/mycampaign.php

myCampaign-created campaign

---

frontend/views/campaign/mycampaign.php
frontend/views/campaign/show.php
frontend/views/campaign/view.php

Explore campaign

---

frontend/views/campaign/view.php

View campaign layouts

---

frontend/assets/ViewCompantAsset.php
frontend/controllers/CampaignController.php
frontend/views/campaign/view.php
frontend/views/campaign/viewcompany.php

View campaign company profile

---

frontend/controllers/CampaignController.php
frontend/models/User.php
frontend/views/campaign/create.php
frontend/views/campaign/delete.php
frontend/views/campaign/mycampaign.php
frontend/views/campaign/view.php
frontend/views/site/index.php

delete campaign page

---

frontend/views/campaign/mycampaign.php
frontend/views/campaign/update.php

updated activity view

---

frontend/views/campaign/create.php
frontend/views/campaign/update.php

changes to create campaign

---

frontend/controllers/CampaignController.php
frontend/controllers/SiteController.php
frontend/views/campaign/myintroduction.php
frontend/views/campaign/view.php
frontend/views/layouts/footer.php
frontend/views/user/update.php

View profile from others

---

frontend/controllers/CampaignController.php
frontend/views/campaign/myintroduction.php

Introduction page for user

---

backend/controllers/UserBackendController.php
backend/views/user-backend/profile.php
backend/views/user-backend/update.php

Backend user profile

---

backend/controllers/UserBackendController.php
backend/views/user-backend/profile.php
frontend/controllers/CampaignController.php
frontend/views/campaign/myintroduction.php
frontend/views/campaign/view.php
frontend/views/campaign/viewcompany.php

View introduction

---

frontend/views/campaign/view.php
frontend/views/campaign/viewcompany.php

View profile modal

---

frontend/controllers/CampaignController.php
frontend/views/campaign/myintroduction.php

Remove duplication

---

frontend/views/campaign/mycampaign.php
frontend/views/campaign/myintroduction.php

Change the route of campaign image call

Change the route of campaign image call

---

backend/views/layouts/header.php
backend/views/site/index.php

Backend index

---

frontend/controllers/CampaignController.php
frontend/models/Campaign.php
frontend/models/Location.php
frontend/views/campaign/create.php
frontend/views/campaign/new.php
frontend/views/layouts/header.php
frontend/views/site/index.php

updated campaign create

---

backend/controllers/EmailController.php
backend/models/Email.php
backend/views/email/_form.php
backend/views/email/index.php
backend/views/site/index.php

Backend send email to single receiver

Backend send email to single

---

frontend/views/campaign/create.php
frontend/views/campaign/mycampaign.php

edited the alignment in create campaign page

edited the alignment in create campaign page

---

composer.lock
frontend/views/campaign/campaign_content.php

View campaign video

---

frontend/views/campaign/campaign_comments.php
frontend/views/campaign/campaign_faq.php
frontend/views/campaign/fund.php

Fund campaign layouts

---

frontend/views/campaign/viewcompany.php

View company

---

frontend/controllers/CampaignController.php

delete campaign updated

---

frontend/controllers/CampaignController.php
frontend/views/campaign/create.php
frontend/views/campaign/mycampaign.php
frontend/views/campaign/updatepublished.php

post an update

---

frontend/views/campaign/campaign_content.php
frontend/views/campaign/preview.php
frontend/views/campaign/view.php

display video

---

frontend/controllers/CampaignController.php
frontend/views/campaign/viewcompany.php

Explore campaigns

---

frontend/views/campaign/campaign_update.php
frontend/views/campaign/updatepublished.php
frontend/views/campaign/view.php

modal view in update

---

frontend/views/campaign/mycampaign.php

Mycampaign Image display

---

frontend/controllers/CampaignController.php

Introduction display

---

composer.json
composer.lock
frontend/controllers/CampaignController.php
frontend/views/campaign/campaign_update.php
frontend/views/campaign/preview.php
frontend/views/campaign/view.php

submit for review button

---

frontend/controllers/CampaignController.php
frontend/views/campaign/mycampaign.php
frontend/views/campaign/view.php

changes to view campaign

---

frontend/views/campaign/view.php

Calculate campaign deadline

---

frontend/views/campaign/preview.php
frontend/views/campaign/view.php

View and review campaign

---

frontend/controllers/CampaignController.php
frontend/models/Campaign.php
frontend/views/campaign/create.php
frontend/views/campaign/view.php

Send email when moderation

---

backend/controllers/CampaignController.php
backend/models/Campaign.php

Moderation campaign send email to author when the campaign be published

Moderation campaign send email

---

frontend/controllers/WalletController.php
frontend/models/Wallet.php
frontend/models/WalletSearch.php
frontend/views/campaign/campaign_update.php
frontend/views/layouts/header.php
frontend/views/wallet/_form.php
frontend/views/wallet/_search.php
frontend/views/wallet/create.php
frontend/views/wallet/index.php
frontend/views/wallet/update.php
frontend/views/wallet/view.php

creation of wallet UI

---

frontend/controllers/WalletController.php
frontend/rpc/jsonRPCClient.php
frontend/views/campaign/view.php
frontend/views/wallet/new.php

JsonRPCClient - suggest_brain_key (works for wallet api)

JsonRPCClient

---

frontend/views/campaign/preview.php
frontend/views/campaign/view.php

Calculate the days to go

---

frontend/views/campaign/preview.php
frontend/views/campaign/view.php

Change country list and display

Change country list and display

---

frontend/models/Campaign.php

campaign model

---

frontend/views/campaign/create.php

updated rewards to perks

---

frontend/views/campaign/create.php

changes to perks

---

backend/views/campaign/_form.php

Backend view campaign page

---

frontend/views/campaign/create.php

date widget

---

frontend/views/campaign/create.php

video description

---

frontend/views/campaign/create.php

toggle video

---

frontend/views/campaign/create.php
frontend/views/campaign/edit.php

updated edit campaign

---

frontend/views/campaign/view.php

View campaign video link

---

composer.json
composer.lock
frontend/config/main.php
frontend/controllers/CampaignController.php
frontend/controllers/SiteController.php
frontend/models/Company.php
frontend/views/site/login.php

fb login initial

---

frontend/views/campaign/show.php
frontend/views/campaign/view.php

View campaign days

---

frontend/views/campaign/preview.php

preview video display

---

frontend/views/site/index.php

Homepage display

---

backend/config/main.php
backend/views/campaign/_form.php
backend/views/category/update.php

Backend campaign review and category update

Backend campaign review and category update

---

backend/views/frontend-user/view.php
backend/views/user-backend/index.php
backend/views/user-backend/view.php

Backend backend and frontend user view

Backend backend and frontend user view

---

composer.json
composer.lock
frontend/tests/unit/UserTest.php

Unit Testing

---

frontend/controllers/SiteController.php
frontend/controllers/WalletController.php

fb login works

---

backend/views/campaign/index.php
backend/views/category/index.php
composer.lock
frontend/controllers/CampaignController.php
frontend/controllers/SiteController.php
frontend/views/campaign/campaign_comments.php
frontend/views/campaign/view.php
frontend/views/layouts/header.php
frontend/views/site/index.php
frontend/views/site/login.php
frontend/views/site/signup.php

updated the db to the actual campaign like db

updated the db to the actual campaign like db

---

frontend/tests/unit/CampaignTest.php
frontend/tests/unit/CommentTest.php
frontend/tests/unit/CompanyTest.php
frontend/tests/unit/FaqTest.php
frontend/tests/unit/LocationTest.php
frontend/tests/unit/RewardTest.php
frontend/tests/unit/TokenTest.php
frontend/tests/unit/UserTest.php
frontend/tests/unit/WalletTest.php

Frontend unit test

---

backend/tests/unit.suite.yml
backend/tests/unit/CampaignTest.php
frontend/tests/unit/CampaignTest.php

Backend unit test

---

backend/tests/unit/BackendUserTest.php
backend/tests/unit/CampaignTest.php
backend/tests/unit/CategoryTest.php

Backend unit testing

---

backend/tests/unit/LocationTest.php

Location unit test

---

backend/tests/unit/BackendUserTest.php

Unit test for backend user

---

frontend/assets/WalletAsset.php
frontend/controllers/WalletController.php
frontend/views/layouts/header.php
frontend/views/wallet/mywallet.php
frontend/views/wallet/new.php
frontend/web/css/wallet/method.css

views for wallet

---

composer.json
composer.lock
frontend/assets/WalletAsset.php
frontend/config/main.php
frontend/controllers/WalletController.php
frontend/models/Wallet.php
frontend/rpc/jsonRPCClient.php
frontend/views/layouts/header.php
frontend/views/wallet/create.php
frontend/views/wallet/mywallet.php
frontend/views/wallet/new.php
frontend/web/css/wallet/tab.css

mywallet rpc calls

---

backend/controllers/EmailController.php
frontend/controllers/CampaignController.php
frontend/models/Campaign.php
frontend/views/campaign/myintroduction.php
frontend/views/campaign/view.php
frontend/views/site/index.php

submit for review campaign

---

backend/models/Campaign.php
frontend/models/Campaign.php
frontend/views/site/index.php

email format

---

backend/views/campaign/_form.php
frontend/views/site/index.php

Campaign status

---

frontend/controllers/CampaignController.php
frontend/controllers/WalletController.php
frontend/views/campaign/fund.php
frontend/views/wallet/mywallet.php

rpc call for fund campaign

---

frontend/controllers/CampaignController.php
frontend/controllers/WalletController.php
frontend/views/campaign/edit.php
frontend/views/campaign/view.php
frontend/views/wallet/mywallet.php

changes to edit rewards

---

backend/controllers/EmailController.php
common/mail/mailTemplate-html.php
common/mail/mailTemplate-text.php

Backend sendmail template

---

backend/views/email/index.php
frontend/controllers/CampaignController.php

Backend email layouts

---

backend/views/email/_form.php
frontend/controllers/CampaignController.php
frontend/controllers/QuestionController.php
frontend/models/Question.php
frontend/models/QuestionSearch.php
frontend/views/campaign/campaign_faq.php
frontend/views/question/_form.php
frontend/views/question/_search.php
frontend/views/question/create.php
frontend/views/question/index.php
frontend/views/question/update.php
frontend/views/question/view.php

Campaign FAQ modal

---

common/mail/FAQtemplate-html.php
common/mail/FAQtemplate-text.php
frontend/controllers/QuestionController.php
frontend/models/Question.php

FAQ send email

---

frontend/controllers/CampaignController.php
frontend/models/Campaign.php
frontend/models/Company.php
frontend/models/Token.php

included date validation

---

frontend/controllers/CampaignController.php
frontend/models/Campaign.php
frontend/models/Company.php
frontend/models/Token.php
frontend/views/campaign/create.php
frontend/views/campaign/edit.php

updates to validations

---

frontend/controllers/CampaignController.php
frontend/models/Token.php
frontend/views/campaign/create.php
frontend/views/campaign/edit.php

updates to edit campaign page

---

frontend/controllers/CampaignController.php
frontend/models/Fund.php
frontend/views/campaign/mycampaign.php

fixed issues with view activites

fixed issues with view activites

---

backend/config/main.php
frontend/config/main.php
frontend/controllers/CampaignController.php
frontend/models/Company.php
frontend/models/Industry.php
frontend/views/campaign/create.php
frontend/views/layouts/main.php
frontend/views/site/login.php

Company industry dropdown list

company industry dropdown list

---

frontend/controllers/CampaignController.php
frontend/views/campaign/edit.php
frontend/views/campaign/mycampaign.php
frontend/views/layouts/main.php

layout in Perks fixed

---

frontend/controllers/CampaignController.php
frontend/models/Reward.php
frontend/views/campaign/edit.php

edit perks works

---

frontend/controllers/CampaignController.php
frontend/models/Reward.php
frontend/views/campaign/create.php
frontend/views/campaign/edit.php

validation added to rewards

---

frontend/controllers/CampaignController.php
frontend/views/campaign/mycampaign.php

Activities displays updates

---

frontend/controllers/WalletController.php
frontend/views/campaign/postupdate.php
frontend/views/wallet/mywallet.php

rpc call for transaction history

rpc call for transaction history

---

backend/views/frontend-user/view.php

Delete update button on frontend user view

Delete update button on frontend user view

---

frontend/controllers/WalletController.php
frontend/views/campaign/campaign_update.php
frontend/views/campaign/postupdate.php
frontend/views/campaign/test2.php
frontend/views/wallet/create.php
frontend/views/wallet/mywallet.php

added title to wallet page

---

composer.lock
frontend/config/main.php
frontend/controllers/CampaignController.php

email triggered

---

frontend/controllers/CampaignController.php
frontend/views/campaign/show.php
frontend/views/campaign/view.php

updated progress bar

---

frontend/controllers/CampaignController.php

edit published campaign

---

frontend/controllers/CampaignController.php
frontend/views/campaign/create.php
frontend/views/campaign/preview.php
frontend/views/campaign/view.php
frontend/views/site/index.php

bug fixes in view and index page

bug fixes in view and index page

---

frontend/views/campaign/preview.php
frontend/views/campaign/view.php

Remove the submit for review button

Remove the submit for review button

---

frontend/views/campaign/preview.php

changed font in preview page
